[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200  # You can adjust the number of optimization runs
via_ir = true  # Enable IR compilation

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
